CREATE DATABASE <REPLACE WITH YOUR DATABASE NAME>;

CREATE TABLE <REPLACE WITH YOUR DATABASE NAME>.<REPLACE WITH YOUR TABLE NAME> (
  map_key       VARCHAR(256)    PRIMARY KEY,
  class_name    VARCHAR(256) NOT NULL,
  bytes         BLOB            NULL
)
DEFAULT CHARSET =latin1;

CREATE USER '<REPLACE WITH A USER>' IDENTIFIED BY '<REPLACE WITH A PASSWORD>';

GRANT ALL PRIVILEGES ON <REPLACE WITH YOUR DATABASE NAME>.<REPLACE WITH YOUR TABLE NAME> TO '<REPLACE WITH A USER>'@'%' WITH GRANT OPTION;